# Generated by Django 3.1.7 on 2021-03-05 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0002_auto_20210304_2331'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='highprice',
            name='high_price',
        ),
        migrations.RemoveField(
            model_name='lowprice',
            name='low_price',
        ),
        migrations.AddField(
            model_name='highprice',
            name='highprice',
            field=models.DecimalField(decimal_places=5, default='SOME STRING', max_digits=10),
        ),
        migrations.AddField(
            model_name='lowprice',
            name='lowprice',
            field=models.DecimalField(decimal_places=5, default='SOME STRING', max_digits=10),
        ),
    ]
