# Generated by Django 3.1.7 on 2021-03-05 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0005_auto_20210305_0934'),
    ]

    operations = [
        migrations.CreateModel(
            name='PricesLimits',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lowprice', models.FloatField(default=None)),
                ('highprice', models.FloatField(default=None)),
            ],
        ),
        migrations.DeleteModel(
            name='HighPrice',
        ),
        migrations.DeleteModel(
            name='LowPrice',
        ),
        migrations.AlterField(
            model_name='stock',
            name='ticker',
            field=models.CharField(max_length=10),
        ),
    ]
