# Generated by Django 3.1.7 on 2021-03-05 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0006_auto_20210305_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='priceslimits',
            name='highprice',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='priceslimits',
            name='lowprice',
            field=models.FloatField(default=0.0),
        ),
    ]
