# Generated by Django 3.1.7 on 2021-03-05 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0007_auto_20210305_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='priceslimits',
            name='highprice',
            field=models.FloatField(default=None),
        ),
        migrations.AlterField(
            model_name='priceslimits',
            name='lowprice',
            field=models.FloatField(default=None),
        ),
    ]
