# Generated by Django 3.1.7 on 2021-03-06 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0008_auto_20210305_1621'),
    ]

    operations = [
        migrations.CreateModel(
            name='LowerLimit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lowprice', models.FloatField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='UpperLimit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('highprice', models.FloatField(default=None)),
            ],
        ),
        migrations.DeleteModel(
            name='PricesLimits',
        ),
    ]
