# Generated by Django 3.1.7 on 2021-03-06 02:21

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0009_auto_20210305_2141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lowerlimit',
            name='lowprice',
            field=models.FloatField(default=Decimal('0')),
        ),
        migrations.AlterField(
            model_name='upperlimit',
            name='highprice',
            field=models.FloatField(default=Decimal('0')),
        ),
    ]
