# Generated by Django 3.1.7 on 2021-03-06 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0010_auto_20210305_2321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lowerlimit',
            name='lowprice',
            field=models.FloatField(default=None),
        ),
        migrations.AlterField(
            model_name='upperlimit',
            name='highprice',
            field=models.FloatField(default=None),
        ),
    ]
